const ChannelsList = [
    { name: "🏰｜welcome", category: "Information", type: "text" },
    { name: "📜｜rules", category: "Information", type: "text" },
    { name: "📢｜announcements", category: "Information", type: "text" },
    { name: "📣｜system-messages", category: "Information", type: "text" },
    { name: "🥃｜after-dark-access", category: "Information", type: "text" },
    { name: "📋｜server-suggestions", category: "Information", type: "text" },
    { name: "💚｜leaderboards", category: "Information", type: "text" },

    { name: "🗳｜votings", category: "Events", type: "text" },
    { name: "📖｜wordle", category: "Events", type: "text" },
    { name: "🧪｜nimos-devies", category: "Events", type: "text" },
    { name: "♦️｜steven-universe-watch-party", category: "Events", type: "text" },

    { name: "💬｜general", category: "General Stuff", type: "text" },
    { name: "😂｜funposting-and-memes", category: "General Stuff", type: "text" },
    { name: "💩｜cursed-shitpost-spam", category: "General Stuff", type: "text" },
    { name: "✨｜advertising-yourself", category: "General Stuff", type: "text" },
    { name: "⏰｜slowmode", category: "General Stuff", type: "text" },
    { name: "🤖｜bot-party", category: "General Stuff", type: "text" },
    { name: "🇵🇱｜the-polish-chat", category: "General Stuff", type: "text" },
    { name: "🇳🇱｜the-dutch-chat", category: "General Stuff", type: "text" },

    { name: "✈｜aerospace", category: "Interests", type: "text" },
    { name: "🧹｜ai-generated-images", category: "Interests", type: "text" },
    { name: "🎥｜animation-and-cgi", category: "Interests", type: "text" },
    { name: "🥷｜anime", category: "Interests", type: "text" },
    { name: "🏢｜architecture", category: "Interests", type: "text" },
    { name: "🎨｜art-sharing", category: "Interests", type: "text" },
    { name: "🍕｜culinary", category: "Interests", type: "text" },
    { name: "💠｜design", category: "Interests", type: "text" },
    { name: "👯｜femboy", category: "Interests", type: "text" },
    { name: "😸｜furry-fursuits-vrfurs", category: "Interests", type: "text" },
    { name: "✂｜modeling", category: "Interests", type: "text" },
    { name: "🚗｜motorization", category: "Interests", type: "text" },
    { name: "🎬｜movies-and-shows", category: "Interests", type: "text" },
    { name: "🎵｜music", category: "Interests", type: "text" },
    { name: "🎭｜musicals", category: "Interests", type: "text" },
    { name: "🌱｜nature", category: "Interests", type: "text" },
    { name: "🐾｜paw-posting", category: "Interests", type: "text" },
    { name: "📷｜photography", category: "Interests", type: "text" },
    { name: "💻｜programming", category: "Interests", type: "text" },
    { name: "🎲｜rpg", category: "Interests", type: "text" },
    { name: "⚽｜sports", category: "Interests", type: "text" },
    { name: "🔬｜technology", category: "Interests", type: "text" },
    { name: "📚｜quotes", category: "Interests", type: "text" },
    { name: "🗺｜traveling", category: "Interests", type: "text" },

    { name: "🎮｜gaming-general", category: "Gaming Stuff", type: "text" },
    { name: "🔩｜automation-games", category: "Gaming Stuff", type: "text" },
    { name: "🙉｜apex-legends", category: "Gaming Stuff", type: "text" },
    { name: "🎈｜bloons", category: "Gaming Stuff", type: "text" },
    { name: "🪨｜deep-cock-galactic", category: "Gaming Stuff", type: "text" },
    { name: "🧸｜fnaf", category: "Gaming Stuff", type: "text" },
    { name: "🚌｜fortnite", category: "Gaming Stuff", type: "text" },
    { name: "🧙｜league-of-legends", category: "Gaming Stuff", type: "text" },
    { name: "🟫｜minecraft", category: "Gaming Stuff", type: "text" },
    { name: "⌚｜overwatch", category: "Gaming Stuff", type: "text" },
    { name: "🌱｜pikmin", category: "Gaming Stuff", type: "text" },
    { name: "🎢｜planet-coaster", category: "Gaming Stuff", type: "text" },
    { name: "🐠｜pokémon", category: "Gaming Stuff", type: "text" },
    { name: "🏎｜racing-games", category: "Gaming Stuff", type: "text" },
    { name: "🔳｜roblox", category: "Gaming Stuff", type: "text" },
    { name: "⚽｜rocket-league", category: "Gaming Stuff", type: "text" },
    { name: "💲｜sims", category: "Gaming Stuff", type: "text" },
    { name: "🌾｜stardew-valley", category: "Gaming Stuff", type: "text" },
    { name: "🌳｜terraria", category: "Gaming Stuff", type: "text" },
    { name: "🥽｜vr", category: "Gaming Stuff", type: "text" },
    { name: "💦｜the-binding-of-isaac", category: "Gaming Stuff", type: "text" },

    { name: "🦇｜bat-posting", category: "Animal Posting", type: "text" },
    { name: "🐇｜bunny-posting", category: "Animal Posting", type: "text" },
    { name: "🍊｜capybara-posting", category: "Animal Posting", type: "text" },
    { name: "🐱｜cat-posting", category: "Animal Posting", type: "text" },
    { name: "🦌｜deer-posting", category: "Animal Posting", type: "text" },
    { name: "🐶｜dog-posting", category: "Animal Posting", type: "text" },
    { name: "🐉｜dragon-posting", category: "Animal Posting", type: "text" },
    { name: "🦊｜fox-posting", category: "Animal Posting", type: "text" },
    { name: "🐊｜gator-posting", category: "Animal Posting", type: "text" },
    { name: "🐴｜horse-posting", category: "Animal Posting", type: "text" },
    { name: "🦈｜landshark-posting", category: "Animal Posting", type: "text" },
    { name: "🦎｜lizor-posting", category: "Animal Posting", type: "text" },
    { name: "🐵｜monkey-posting", category: "Animal Posting", type: "text" },
    { name: "🦦｜otter-posting", category: "Animal Posting", type: "text" },
    { name: "🦝｜raccoon-posting", category: "Animal Posting", type: "text" },
    { name: "🐺｜wolf-posting", category: "Animal Posting", type: "text" },
    { name: "🐾｜other-animals-posting", category: "Animal Posting", type: "text" },

    { name: "🎤｜vc-text-conversation", category: "Voice Channels", type: "text" },
    { name: "🎼｜vc-music-commands", category: "Voice Channels", type: "text" },
    { name: "Talking", category: "Voice Channels", type: "voice" },
    { name: "Gaming", category: "Voice Channels", type: "voice" },
    { name: "Arting", category: "Voice Channels", type: "voice" },
    { name: "Coding", category: "Voice Channels", type: "voice" },
    { name: "🔴 Streaming /  Recording", category: "Voice Channels", type: "voice" },
    { name: "Admins Private Party", category: "Voice Channels", type: "voice" },
    { name: "🔇AFK", category: "Voice Channels", type: "voice" },

    { name: "📢｜lagoona-smp-changelog", category: "LagoonaSMP Minecraft Server", type: "text" },
    { name: "💬｜lagoonasmp-chat", category: "LagoonaSMP Minecraft Server", type: "text" },
    { name: "🎼｜lagoonasmp-music-commands", category: "LagoonaSMP Minecraft Server", type: "text" },
    { name: "🎤｜LagoonaSMP  VC", category: "LagoonaSMP Minecraft Server", type: "voice" },

    { name: "🎭｜roleplay", category: "Roleplaying", type: "text" },
    { name: "😈｜roleplay-nsfw", category: "Roleplaying", type: "text" },

    { name: "🔞｜after-dark-talks", category: "After Dark", type: "text" },
    { name: "🌭｜after-dark-memes", category: "After Dark", type: "text" },
    { name: "📏｜after-dark-straight", category: "After Dark", type: "text" },
    { name: "🍑｜after-dark-female", category: "After Dark", type: "text" },
    { name: "🍆｜after-dark-male", category: "After Dark", type: "text" },
    { name: "😳｜after-dark-kinky", category: "After Dark", type: "text" },
    { name: "🎤｜lewd-talkies-text-conversation", category: "After Dark", type: "text" },
    { name: "🎼｜lewd-talkies-music-commands", category: "After Dark", type: "text" },
    { name: "Lewd Talkies", category: "After Dark", type: "voice" },

    { name: "🤗｜venting", category: "Venting", type: "text" },

    { name: "🌈｜rainbow-six-siege", category: "Archive", type: "text" },
    { name: "🔫｜call-of-duty", category: "Archive", type: "text" },
    { name: "💠｜paladins", category: "Archive", type: "text" },
    { name: "⭐｜starboard", category: "Archive", type: "text" },
    { name: "💀｜dont-starve", category: "Archive", type: "text" },
    { name: "🥜｜november", category: "Archive", type: "text" },
    { name: "✏｜drawpile", category: "Archive", type: "text" },
    { name: "😍｜valentines-with-among-us", category: "Archive", type: "text" },
    { name: "🎄｜marry-christmas", category: "Archive", type: "text" },

    { name: "bots-log", category: "Server Log", type: "text" },
    { name: "amin-log", category: "Server Log", type: "text" },
    { name: "activities-log", category: "Server Log", type: "text" },
    { name: "vc-log", category: "Server Log", type: "text" },
    { name: "testies", category: "Server Log", type: "text" },
    { name: "sever-staff", category: "Server Log", type: "text" },
    { name: "server-console", category: "Server Log", type: "text" },
    { name: "nimos-database", category: "Server Log", type: "text" },
    { name: "archive", category: "Server Log", type: "text" },
    { name: "admin-ifno", category: "Server Log", type: "text" },
    { name: "🗑-trash", category: "Server Log", type: "text" },

    { name: "📝｜autoroles", category: "Unlisted Archive", type: "text" },
    { name: "voting-mido-case-2025-03-26", category: "Unlisted Archive", type: "text" },
    { name: "nimo-is-a-problem", category: "Unlisted Archive", type: "text" },
    { name: "voting-herosima-case-01", category: "Unlisted Archive", type: "text" },
]

export default ChannelsList
